# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  format:
    cmds:
      - uv run ruff format app/
      - uv run ruff format tests/
      - uv run ruff check --fix app/
      - uv run ruff check --fix tests/